### ISSUE TITLE
HTTP status code diferentes no título e na asserção de teste

### ISSUE THREAD

**Issue by karlmarxd** [instruct-br/teste-backend-remoto#1]
https://github.com/instruct-br/teste-backend-remoto/blob/69e2dadcedfc64543ddc261b0b2afa127c2fbb45/tests-open.js#L82-L83

Olá!
No titulo do teste diz que a requisição deve retornar status 404, mas está sendo feita asserção para verificar se o status retorna 403.

Qual dos dois códigos a requisição deve retornar?

**Comment by oesgalha** [comment]
Olá!

É pra retornar o 403 mesmo, subi uma correção nesse texto.

Muito obrigado por reportar o problema.
